package com.testing.poc.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-10T13:26:04.131-05:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://ws.poc.testing.com/", name = "OperationWS")
@XmlSeeAlso({ObjectFactory.class})
public interface OperationWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.poc.testing.com/OperationWS/addRequest", output = "http://ws.poc.testing.com/OperationWS/addResponse")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.poc.testing.com/", className = "com.testing.poc.jaxws.client.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.poc.testing.com/", className = "com.testing.poc.jaxws.client.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
