
package com.testing.poc.jaxws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-10T13:26:04.022-05:00
 * Generated source version: 3.0.4
 * 
 */
public final class OperationWS_OperationWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.poc.testing.com/", "OperationWSService");

    private OperationWS_OperationWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OperationWSService.WSDL_LOCATION;
        //jetty
        wsdlURL = new URL("http://localhost:8080/app");
        
        //weblogic
        //wsdlURL = new URL("http://localhost:11002/jaxws-poc/app"); 
        OperationWSService ss = new OperationWSService(wsdlURL, SERVICE_NAME);
        OperationWS port = ss.getOperationWSPort();  
        
        {
        System.out.println("Invoking add...");
        int _add_arg0 = 15;
        int _add_arg1 = 10;

        int _add__return = port.add(_add_arg0, _add_arg1);
        System.out.println("add.result=" + _add__return);


        }

        System.exit(0);
    }

}
